Repository OAI/OpenAPI-Specification, pull requests merged in 2024-02, with the labels that each got.

#3233 Content-Type for properties with type string and contentEncoding
  versions/3.1.1.md
Labels: clarification, media and encoding

#3258 Use $ref to definitions in oneOf for Parameter locations
  schemas/v3.0/schema.yaml
Labels: Schema

#3355 Fix 3.1 Path Item schema
  schemas/v3.1/schema.yaml
Labels: Schema

#3455 Drop `uri-reference` format for template URLs
  schemas/v3.0/schema.yaml
  schemas/v3.1/schema.yaml
Labels: Schema

#3387 Describe OpenAPI entry point in OpenAPI description docs
  versions/3.1.1.md
Labels: clarification

#3554 Always checkout JavaScript environment from main
  .github/workflows/schema-tests.yaml
  .github/workflows/validate-markdown.yaml
Labels: javascript

#3522 Update weekly meeting agenda to direct topic suggestions and add housekeeping time
  .github/templates/agenda.md
Labels: Housekeeping

#3551 Update SIGs list, improve formatting and links
  SPECIAL_INTEREST_GROUPS.md
Labels: Housekeeping

#3548 fix: GitHub changed markdown rendering for headings/anchors
  versions/2.0.md
  versions/3.0.0.md
  versions/3.0.1.md
  versions/3.0.2.md
  versions/3.0.3.md
  versions/3.1.0.md
Labels: bug

#3568 Fix validate script
  scripts/validate.js
  scripts/validate.mjs
Labels: javascript

#3214 Copy Versions section from 3.1.1-dev into 3.0.4-dev
  versions/3.0.4.md
Labels: clarification

#3570 Align the markdown workflow's JavaScript environment with the others
  .github/workflows/validate-markdown.yaml
Labels: javascript

#3558 Sync validate-markdown workflow with main (3.0.4)
  .github/workflows/validate-markdown.yaml
Labels: javascript

#3559 Sync validate-markdown workflow with main (3.1.1)
  .github/workflows/validate-markdown.yaml
Labels: javascript

#3560 Sync validate-markdown workflow with main (3.2.0)
  .github/workflows/validate-markdown.yaml
Labels: javascript

#3413 Generalize description of password data type
  versions/3.1.1.md
Labels: clarification

#3465 whitespace and quoting fixes in json and yaml examples (v3.1.1)
  versions/3.1.1.md
Labels: examples

#3466 whitespace and quoting fixes in json and yaml examples (v3.2.0)
  versions/3.2.0.md
Labels: examples

#3549 whitespace and quoting fixes in json and yaml examples (v3.0.4)
  versions/3.0.4.md
Labels: examples

#3531 Generalize description of password data type in registry
  registries/_format/password.md
Labels: format-registry

#3580 Clean guidelines
  guidelines/EXTENSIONS.md
  guidelines/v2.0/EXTENSIONS.md
  guidelines/v2.0/README.md
  guidelines/v2.0/REUSE.md
Labels: Housekeeping

#3390 Add structured fields primitive types to format registry
  registries/_format/sf-binary.md
  registries/_format/sf-boolean.md
  registries/_format/sf-decimal.md
  registries/_format/sf-integer.md
  registries/_format/sf-string.md
  registries/_format/sf-token.md
Labels: format-registry, Needs author feedback
