Repository OAI/OpenAPI-Specification, pull requests merged in 2024-11, with the labels that each got.

#4166 main: move YAML examples to test fixtures, remove examples folder
  .github/workflows/convert-examples-to-json.yaml
  examples/v2.0/json/api-with-examples.json
  examples/v2.0/json/petstore-expanded.json
  examples/v2.0/json/petstore-minimal.json
  examples/v2.0/json/petstore-separate/common/Error.json
  examples/v2.0/json/petstore-separate/spec/NewPet.json
  examples/v2.0/json/petstore-separate/spec/Pet.json
  examples/v2.0/json/petstore-separate/spec/parameters.json
  examples/v2.0/json/petstore-separate/spec/swagger.json
  examples/v2.0/json/petstore-simple.json
  examples/v2.0/json/petstore-with-external-docs.json
  examples/v2.0/json/petstore.json
  examples/v2.0/json/uber.json
  examples/v2.0/yaml/api-with-examples.yaml
  examples/v2.0/yaml/petstore-expanded.yaml
  examples/v2.0/yaml/petstore-minimal.yaml
  examples/v2.0/yaml/petstore-separate/common/Error.yaml
  examples/v2.0/yaml/petstore-separate/spec/NewPet.yaml
  examples/v2.0/yaml/petstore-separate/spec/Pet.yaml
  examples/v2.0/yaml/petstore-separate/spec/parameters.yaml
  examples/v2.0/yaml/petstore-separate/spec/swagger.yaml
  examples/v2.0/yaml/petstore-simple.yaml
  examples/v2.0/yaml/petstore-with-external-docs.yaml
  examples/v2.0/yaml/petstore.yaml
  examples/v2.0/yaml/uber.yaml
  examples/v3.0/api-with-examples.json
  examples/v3.0/callback-example.json
  examples/v3.0/link-example.json
  examples/v3.0/petstore-expanded.json
  examples/v3.0/petstore.json
  examples/v3.0/uspto.json
  examples/v3.1/non-oauth-scopes.json
  examples/v3.1/webhook-example.json
  tests/md2html/md2html.test.mjs
  tests/v3.0/pass/api-with-examples.yaml
  tests/v3.0/pass/callback-example.yaml
  tests/v3.0/pass/link-example.yaml
  tests/v3.0/pass/petstore-expanded.yaml
  tests/v3.0/pass/petstore.yaml
  tests/v3.0/pass/uspto.yaml
  tests/v3.0/schema.test.mjs
  tests/v3.1/examples.test.js
  tests/v3.1/pass/non-oauth-scopes.yaml
  tests/v3.1/pass/webhook-example.yaml
  vitest.config.mjs
Labels: Housekeeping

#4162 Schema Publish workflow
  .github/workflows/schema-publish.yaml
  schemas/v3.1/dialect.yaml
  schemas/v3.1/meta.yaml
  scripts/schema-publish.sh
  scripts/yaml2json/yaml2json.js
Labels: Housekeeping, script

#4180 main: respec workflow - same reviewers as for schema publishing
  .github/workflows/respec.yaml
Labels: Housekeeping

#4189 The schemas are (mostly) not metaschemas
  .github/workflows/schema-publish.yaml
Labels: Schema, Housekeeping, script

#4182 Use GitHub project for contributor lists instead of a file
  CONTRIBUTORS.md
Labels: Housekeeping

#4196 v3.1-dev: Validate src/oas.md
  .github/workflows/validate-markdown.yaml
  package.json
Labels: Housekeeping

#4186 CONTRIBUTING.md: Schema development process, improved mermaid diagram, etc.
  CONTRIBUTING.md
Labels: Schema, Process

#4184 Add criteria for minor and patch releases
  CONTRIBUTING.md
Labels: Housekeeping

#4199 dev: Validate src/oas.md
  .github/workflows/validate-markdown.yaml
  package.json
Labels: Housekeeping

#4204 Update PR template for new branching strategy.
  .github/pull_request_template.md
Labels: Housekeeping

#4173 main: schema test coverage
  package.json
  scripts/schema-test-coverage.mjs
  scripts/schema-test-coverage.sh
Labels: Schema, Housekeeping

#4191 respec workflow: create symlinks for spec minor versions
  scripts/md2html/build.sh
Labels: Housekeeping, github_actions

#4193 gh-pages: ignore spec minor-version symlinks
  _includes/specification-version-list.md
Labels: Housekeeping

#4198 dev: schema tests use src/schemas/validation
  tests/v3.1/schema.test.mjs
Labels: Schema, Housekeeping

#4164 gh-pages: skip dialect base & meta base
  index.md
Labels: Schema, Housekeeping

#4226 gh-pages: Generalize registry site to publications
  _config.yml
  index.md
Labels: script, registries

#4188 Migrate relevant 3.2 commits to the new branch structure
  src/oas.md
Labels: approved pr port
