Repository OAI/OpenAPI-Specification, pull requests merged in 2024-03, with the labels that each got.

#3488 Added security considerations document
  SECURITY_CONSIDERATIONS.md
Labels: security, security: meta

#3620 Fix: #3619. Reference IANA media type page.
  SECURITY_CONSIDERATIONS.md
Labels: security, security: meta

#3607 Fix incorrect OpenIDConnect discovery url
  versions/3.0.4.md
Labels: security, security: auth

#3671 Update actions used in respec workflow
  .github/workflows/respec.yaml
Labels: Housekeeping, javascript

#3669 Update GOVERNANCE.md
  GOVERNANCE.md
Labels: Housekeeping

#3673 Replaced a longer draft features section with a proposed proposal process
  DEVELOPMENT.md
Labels: Housekeeping, Process

#3675 small typo fix
  versions/3.2.0.md
Labels: bug

#3674 small typo fix
  versions/3.1.1.md
Labels: bug
