Repository OAI/OpenAPI-Specification, pull requests merged in 2024-07, with the labels that each got.

#3939 Update ReSpec versions for Arazzo
  arazzo/latest.html
  arazzo/v1.0.0.html
Labels: Housekeeping

#3940 Remove need for separate ReSpec clone for Arazzo
  scripts/md2html/md2html.js
Labels: Housekeeping

#3931 3.0.4: sync with 3.1.1
  versions/3.0.4.md
Labels: editorial

#3937 Reorganize and streamline form media type guidance (3.1.1 modified port of 3923, 3929)
  versions/3.1.1.md
Labels: clarification, param serialization, media and encoding, headers

#3948 Remove SIG details; instead link to community/SPECIAL_INTEREST_GROUPS
  SPECIAL_INTEREST_GROUPS.md
Labels: Housekeeping

#3954 Align 3.0.4 with 3.1.1
  versions/3.0.4.md
Labels: editorial

#3953 Align 3.1.1 with 3.0.4
  versions/3.1.1.md
Labels: editorial

#3944 Use latest respec
  package-lock.json
  package.json
  scripts/md2html/build.sh
  scripts/md2html/gist.css
  scripts/md2html/md2html.js
Labels: Housekeeping, script, editorial

#3958 Respec-rendering workflow: improved descriptions
  .github/workflows/respec.yaml
Labels: Housekeeping, github_actions

#3966 Sync 3.0.4 with 3.1.1
  versions/3.0.4.md
Labels: editorial

#3969 3.1.1 formatting improvements
  versions/3.1.1.md
Labels: editorial

#3956 Preserve rfc section links
  scripts/md2html/md2html.js
Labels: editorial, javascript
