Repository OAI/OpenAPI-Specification, pull requests merged in 2024-05, with the labels that each got.

#3718 Clarify `openIdConnectUrl` #3630
  versions/3.1.1.md
Labels: security, clarification

#3744 switch the order of these styles in the tables (3.0.4)
  versions/3.0.4.md
Labels: examples

#3750 Be more clear about "format" validation behavior (3.2.0 port of #3726)
  versions/3.2.0.md
Labels: clarification

#3747 Correctly escape example operationRef URLs (3.1.1 port of #3731)
  versions/3.1.1.md
Labels: bug, examples

#3748 Correctly escape example operationRef URLs (3.2.0 port of #3731)
  versions/3.2.0.md
Labels: bug, examples

#3752 Non-string discriminator values (3.2.0 port of #3728)
  versions/3.2.0.md
Labels: discriminator, clarification

#3754 Clarify spaceDelimited with spaces in values (3.1.1 port of #3723)
  versions/3.1.1.md
Labels: clarification, param serialization

#3755 Clarify spaceDelimited with spaces in values (3.2.0 port of #3723)
  versions/3.2.0.md
Labels: clarification, param serialization

#3756 Clarify wording on encoding field (3.1.1 port of #3724)
  versions/3.1.1.md
Labels: clarification, media and encoding

#3757 Clarify wording on encoding field (3.2.0 port of #3724)
  versions/3.2.0.md
Labels: clarification, media and encoding

#3719 Default encoding object (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization

#3743 fix style=form examples (3.2.0)
  versions/3.2.0.md
Labels: examples

#3742 fix style=form examples (3.0.4)
  versions/3.0.4.md
Labels: examples

#3783 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Housekeeping

#3787 Fix 3.0.4 .gitignore
  .gitignore
Labels: Housekeeping

#3788 Fix 3.1.1 .gitignore
  .gitignore
Labels: Housekeeping

#3768 Explain default Encoding Object behavior (3.2.0 port of #3719)
  versions/3.2.0.md
Labels: clarification, media and encoding

#3760 Clarify constraints on Parameter Object fields (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization

#3766 Backport a clarification about deepObject to 3.0.4
  versions/3.0.4.md
Labels: clarification, param serialization

#3767 Explain default Encoding Object behavior (3.1.1 port of #3719)
  versions/3.1.1.md
Labels: clarification, media and encoding

#3769 Clarify how to model streaming binary data (3.1.1 port of #3729)
  versions/3.1.1.md
Labels: clarification, media and encoding

#3770 Clarify how to model binary data (3.2.0 port of #3727 and #3729
  versions/3.2.0.md
Labels: clarification, media and encoding

#3714 Explain that dynamic refs can implement generics
  versions/3.1.1.md
Labels: schema-object

#3749 operationRef is a URI-reference
  schemas/v3.0/schema.yaml
  schemas/v3.1/schema.yaml
Labels: bug, Schema

#3784 Reinstate validation of JSON Schemas (and examples) in build process
  tests/v3.0/examples.test.js
  tests/v3.1/examples.test.js
  tests/v3.1/schema.test.mjs
Labels: Schema, javascript

#3779 Define "undefined" and "implementation-defined" (3.0.4)
  versions/3.0.4.md
Labels: Process

#3782 Use pinned version of MAINTAINERS.md per spec version
  scripts/md2html/build.sh
  scripts/md2html/md2html.js
Labels: Housekeeping

#3765 Backport case insensitivity note for security schemes to 3.0.4
  versions/3.0.4.md
Labels: clarification, security: meta

#3796 Clarify constraints on Param Obj fields (3.1.1 port of #3760)
  versions/3.1.1.md
Labels: clarification, param serialization

#3797 Clarify constraints on Param Obj fields (3.2.0 port of #3760)
  versions/3.2.0.md
Labels: clarification, param serialization

#3758 Clarify how Schema Objects require full-document parsing (3.1.1)
  versions/3.1.1.md
Labels: clarification, re-use: ref/id resolution

#3807 DEVELOPMENT.md: Criteria for supporting other specifications
  DEVELOPMENT.md
Labels: Housekeeping, Process

#3801 Link for case insensitivity of auth scheme
  versions/3.0.4.md
Labels: security: auth

#3804 Fix "it" -> "its" typo
  versions/3.0.4.md
Labels: bug

#3806 Define "undefined" and "implementation-defined" (3.2.0 port of #3779)
  versions/3.2.0.md
Labels: Process

#3805 Define "undefined" and "implementation-defined" (3.1.1 port of #3449)
  versions/3.1.1.md
Labels: Process

#3795 Explain dynamic refs for generics (3.2.0 port of #3714)
  versions/3.2.0.md
Labels: schema-object, clarification

#3808 MAINTAINERS for 3.0.0
  scripts/md2html/build.sh
Labels: Housekeeping

#3799 Encapsulate page layout
  _includes/alternative-schema-entry.md
  registries/_alternative-schema/jsonSchema.md
  registries/_alternative-schema/xmlSchema.md
Labels: Housekeeping

#3829 Encapsulate page layout for namespaces
  _includes/namespace-entry.md
  registries/_namespace/ms.md
  registries/_namespace/oas-draft.md
  registries/_namespace/sap.md
Labels: Housekeeping

#3830 Encapsulate page layout for formats - Part 1
  _includes/format-entry.md
  registries/_format/base64url.md
  registries/_format/binary.md
  registries/_format/byte.md
  registries/_format/char.md
  registries/_format/commonmark.md
  registries/_format/date-time.md
  registries/_format/date.md
  registries/_format/decimal.md
  registries/_format/decimal128.md
  registries/_format/double-int.md
  registries/_format/double.md
Labels: Housekeeping, format-registry

#3812 Clarify allowEmptyValue -> disregard empty values (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization

#3832 Encapsulate page layout for formats - Part 3
  registries/_format/ipv4.md
  registries/_format/ipv6.md
  registries/_format/iri-reference.md
  registries/_format/iri.md
  registries/_format/json-pointer.md
  registries/_format/media-range.md
  registries/_format/password.md
  registries/_format/regex.md
  registries/_format/relative-json-pointer.md
  registries/_format/sf-binary.md
Labels: Housekeeping, format-registry

#3833 Encapsulate page layout for formats - Part 4
  registries/_format/sf-boolean.md
  registries/_format/sf-decimal.md
  registries/_format/sf-integer.md
  registries/_format/sf-string.md
  registries/_format/sf-token.md
  registries/_format/time.md
  registries/_format/uint8.md
  registries/_format/uri-reference.md
  registries/_format/uri-template.md
  registries/_format/uri.md
  registries/_format/uuid.md
Labels: Housekeeping, format-registry

#3772 Clarify interoperable parsing expectations (3.0.4 port of #3732)
  versions/3.0.4.md
Labels: clarification, re-use: ref/id resolution

#3816 3.1.1 upport of #3801: Link for case insensitivity of auth scheme
  versions/3.1.1.md
Labels: security: auth

#3817 3.2.0 upport of #3801 and #2644: case insensitivity of auth scheme
  versions/3.2.0.md
Labels: security: auth

#3820 Clarify entry/complete document terminology (3.0.4)
  versions/3.0.4.md
Labels: clarification

#3835 Clarify allowEmptyValue -> disregard empty values (3.1.1 port of #3812)
  versions/3.1.1.md
Labels: clarification, param serialization

#3836 Clarify allowEmptyValue -> disregard empty values (3.2.0 port of #3812)
  versions/3.2.0.md
Labels: clarification, param serialization

#3810 Correctly handle appendicies in md2html
  scripts/md2html/md2html.js
Labels: Housekeeping

#3822 Clarify discriminator "*Of" and "mapping" usage (3.0.4)
  versions/3.0.4.md
Labels: discriminator, clarification

#3828 Encapsulate page layout for extensions
  _config.yml
  _includes/extension-entry.md
  registries/_extension/x-twitter.md
Labels: Housekeeping, review

#3842 feat: rendering of the Arazzo Specification
  Gemfile.lock
  README.md
  _config.yml
  arazzo/latest.html
  arazzo/v1.0.0.html
  index.md
  js/respec-arazzo.js
Labels: Housekeeping, javascript
