Repository OAI/OpenAPI-Specification, pull requests merged in 2024-08, with the labels that each got.

#3972 3.0.4: improved RFC section links
  versions/3.0.4.md
Labels: editorial

#3978 Complete normative and informative references
  scripts/md2html/md2html.js
Labels: Housekeeping, editorial, javascript

#3980 Register prefixes reserved by the OAI
  registries/_namespace/oai.md
  registries/_namespace/oas.md
Labels: registries

#3971 respec workflow: improved PR text
  .github/workflows/respec.yaml
Labels: Housekeeping, github_actions

#3984 Begin DEVELOPMENT.md -> CONTRIBUTING.md
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: Housekeeping, Process

#3991 Markdown updates for 3.1.1
  versions/3.1.1.md
Labels: editorial

#3981 gh-pages: remove unused JS files
  js/respec-oai.build.js.map
  js/respec-oai.js
  js/respec-worker.js
Labels: Housekeeping, javascript

#3997 3.0.4: Improved request-response example
  versions/3.0.4.md
Labels: editorial

#3989 New self-identification proposal
  proposals/2024-08-01-Self-Identification.md
Labels: draft:proposal

#3996 3.1.1: Improved external links
  versions/3.1.1.md
Labels: editorial, approved pr port

#4002 Update dependencies to make tests run on Windows
  package-lock.json
Labels: Housekeeping

#4001 3.0.4: minor nits
  versions/3.0.4.md
Labels: editorial

#3992 Build script: no local biblio, use only Specref ids
  scripts/md2html/md2html.js
  tests/md2html/fixtures/.gitattributes
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-new.md
  tests/md2html/fixtures/basic-old.html
  tests/md2html/fixtures/basic-old.md
  tests/md2html/md2html.test.js
Labels: Housekeeping, editorial, javascript

#4006 Build script: improved code blocks
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
Labels: Housekeeping, editorial, javascript

#4008 Build script: improved syntax colors
  scripts/md2html/gist.css
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-old.html
Labels: Housekeeping, script, editorial

#4009 Build script: source-of-truth
  .gitignore
  package-lock.json
  package.json
  scripts/md2html/build.sh
  scripts/md2html/md2html.js
  tests/md2html/README.md
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-new.maintainers
  tests/md2html/fixtures/basic-new.md
  tests/md2html/fixtures/basic-old.html
  tests/md2html/fixtures/basic-old.maintainers
  tests/md2html/fixtures/basic-old.md
  tests/md2html/md2html.test.js
Labels: Housekeeping, script

#4013 gh-pages: specification version lists on landing page
  README.md
  _config.yml
  _includes/specification-version-list.md
  index.md
  rss/feed.xml
Labels: Housekeeping

#4020 3.0.4: replace "property" with "field" or "keyword" where appropriate
  versions/3.0.4.md
Labels: editorial

#4030 gh-pages: fix schema links
  index.md
Labels: Housekeeping

#4021 [Contributors] Add contributors with >25 PRs
  CONTRIBUTORS.md
Labels: Housekeeping

#4031 3.0.4: sync with 3.1.1
  versions/3.0.4.md
Labels: editorial

#4027 Add markdown style guide to CONTRIBUTING
  .markdownlint.yaml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: editorial

#4033 build script: example links point to HTML wrapper on learn site
  package.json
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-old.html
  tests/md2html/fixtures/basic-old.md
  vitest.config.js
Labels: Housekeeping, script, javascript

#4043 3.0.4: link to example on learn site
  versions/3.0.4.md
Labels: editorial

#4032 3.1.1: replace "property" with "field" or "keyword" where appropriate
  versions/3.1.1.md
Labels: Housekeeping, editorial, approved pr port

#4041 markdownlint for 3.1.1.md
  .github/workflows/validate-markdown.yaml
  .markdownlint.yaml
  package.json
Labels: Housekeeping, script

#4050 "Object" definition, "with" in titles, fix level of "Working with Examples"
  versions/3.0.4.md
Labels: editorial

#4045 Clarify data model types and formats
  versions/3.1.1.md
Labels: clarification

#4015 removes the use of integer type from registries format
  _includes/format-entry.md
  registries/_format/double-int.md
  registries/_format/sf-integer.md
  registry/format.md
Labels: format-registry

#4052 "Object" definition, etc. (3.1.1 port of #3050)
  versions/3.1.1.md
Labels: editorial, approved pr port

#4054 3.0.4: use same reference style for draft wright as #4053
  versions/3.0.4.md
Labels: editorial

#4040 3.0.4: tables cleanup & markdownlint
  .github/workflows/validate-markdown.yaml
  .markdownlint.yaml
  package.json
  scripts/format-markdown.sh
  versions/3.0.4.md
Labels: Housekeeping, script

#4055 3.1.1: example for "raw JSON" as message body
  versions/3.1.1.md
Labels: editorial

#4056 3.1.1: tables cleanup
  package.json
  scripts/format-markdown.sh
  versions/3.1.1.md
Labels: script, editorial, approved pr port

#4034 gh-pages: view link and download link for latest JSON schemas
  README.md
  index.md
  oas/3.0/schema/latest.md
  oas/3.1/schema-base/latest.md
  oas/3.1/schema/latest.md
Labels: Housekeeping, editorial

#4025 Markdown updates for 3.2.0
  .github/workflows/validate-markdown.yaml
  .markdownlint.yaml
  package.json
  scripts/format-markdown.sh
  versions/3.2.0.md
Labels: script, editorial, approved pr port

#4060 3.0.4: fix json schema reference
  versions/3.0.4.md
Labels: editorial

#4061 3.1.1: File Upload - difference also to 3.0.x
  versions/3.1.1.md
Labels: editorial
