Repository OAI/OpenAPI-Specification, pull requests merged in 2024-10, with the labels that each got.

#4123 clarifies security requirements wording for 3.1.1
  versions/3.1.1.md
Labels: security, security: config

#4129 clarifies security requirements wording for 3.0.4 (port of #4123)
  versions/3.0.4.md
Labels: security, security: config, approved pr port

#4131 Fix Document vs Description terminology (3.1.1, port of #4100)
  versions/3.1.1.md
Labels: re-use: ref/id resolution, editorial

#4133 gh-pages: no download link for "latest" schema
  index.md
  oas/3.0/schema/2021-09-28.md
  oas/3.0/schema/latest
  oas/3.1/dialect/base.md
  oas/3.1/meta/base.md
  oas/3.1/schema-base/2022-10-07.md
  oas/3.1/schema-base/latest
  oas/3.1/schema/2022-10-07.md
  oas/3.1/schema/latest
Labels: Housekeeping

#4130 Note relative URL-reference resolution ambiguity
  versions/3.0.4.md
Labels: re-use: ref/id resolution

#4137 Run tests with YAML metaschemas
  .github/workflows/schema-tests.yaml
  schemas/v3.0/README.md
  schemas/v3.0/schema.json
  schemas/v3.1/README.md
  schemas/v3.1/dialect/base.schema.json
  schemas/v3.1/meta/base.schema.json
  schemas/v3.1/schema-base.json
  schemas/v3.1/schema.json
  scripts/validate.mjs
  tests/v3.0/examples.test.js
  tests/v3.1/examples.test.js
  tests/v3.1/schema.test.mjs
Labels: Schema, Housekeeping, script

#4142 3.0.4: set release date
  versions/3.0.4.md
Labels: Housekeeping

#4143 3.1.1: set release date
  versions/3.1.1.md
Labels: Housekeeping

#4151 Add 3.0.4 release date to 3.1.1
  versions/3.1.1.md
Labels: bug, editorial

#4145 Update ReSpec-rendered specification versions for Overlay
  overlay/latest.html
  overlay/v1.0.0.html
Labels: Housekeeping

#4146 schemas: add WORK-IN-PROGRESS placeholders, don't mention patch numbers, update terminology
  schemas/v3.0/README.md
  schemas/v3.0/schema.yaml
  schemas/v3.1/README.md
  schemas/v3.1/dialect/base.schema.yaml
  schemas/v3.1/meta/base.schema.yaml
  schemas/v3.1/schema-base.yaml
  schemas/v3.1/schema.yaml
Labels: Schema

#4154 Describe new spec branch and file layout
  CONTRIBUTING.md
  README.md
Labels: Housekeeping
