Repository OAI/OpenAPI-Specification, pull requests merged in 2024-04, with the labels that each got.

#3689 Update agenda.md
  .github/templates/agenda.md
Labels: Housekeeping

#2618 3.1.1 discriminator improvements
  versions/3.1.1.md
Labels: discriminator

#3684 Update 3.1.1 Spec for Style Values
  versions/3.1.1.md
Labels: param serialization

#3686 Update 3.2.0 Spec for Style Values
  versions/3.2.0.md
Labels: param serialization

#3712 Add open projects to the weekly TDC agenda
  .github/templates/agenda.md
Labels: Housekeeping

#3732 Limit interoperable parsing expectations (avoid type conflicts)
  versions/3.1.1.md
Labels: clarification, re-use: ref/id resolution

#3615 ciba-grant-3.2.0.md
  versions/3.2.0.md
Labels: security, security: auth

#3726 Be more clear about `format` support (3.1.1)
  versions/3.1.1.md
Labels: schema-object, clarification

#3731 Correctly escape example operationRef URLs
  versions/3.0.4.md
Labels: bug, examples

#3728 Non-string discriminator values have undefined behavior (3.0.4)
  versions/3.0.4.md
Labels: discriminator, clarification

#3711 Designate our markdown files as our source code
  .gitattributes
Labels: Housekeeping

#3713 Provide a more direct set of issue routing links
  .github/ISSUE_TEMPLATE/config.yml
Labels: Housekeeping

#3724 Clarify wording on when `encoding` is used (3.0.4)
  versions/3.0.4.md
Labels: clarification, media and encoding

#3723 Clarify `spaceDelimited` with spaces (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization

#3727 Clarify how to model binary data in 3.1
  versions/3.1.1.md
Labels: schema-object, media and encoding

#2386 Draft proposal for experimental field
  proposals/2020-10-28-Experimental.md
Labels: draft:proposal

#3729 Clarify how to model streaming binary data
  versions/3.0.4.md
Labels: clarification, media and encoding
