Repository OAI/OpenAPI-Specification, pull requests merged in 2024-09, with the labels that each got.

#4059 3.0.4: absent, empty, or incomplete security list
  versions/3.0.4.md
Labels: security, clarification

#4058 gh-pages: schema list on landing page: call out "view" and "download" links
  index.md
  oas/3.1/dialect/latest.md
  oas/3.1/meta/latest.md
Labels: Housekeeping, editorial

#4064 3.1.1: absent, empty, or incomplete security list
  versions/3.1.1.md
Labels: editorial, approved pr port

#4071 3.1.1: port the undisputed parts of #2140
  versions/3.1.1.md
Labels: approved pr port

#4026 3.2.0: minor nits
  versions/3.2.0.md
Labels: approved pr port

#4035 3.2.0: replace "property" with "field" or "keyword" where appropriate
  versions/3.2.0.md
Labels: editorial, approved pr port

#4079 Markdown links are API Description, not API URLs
  versions/3.1.1.md
Labels: metadata, re-use: ref/id resolution

#4078 Further clarify link operation ambiguity (3.0.4)
  versions/3.0.4.md
Labels: links, clarification, re-use: ref/id resolution

#4077 Clarify complete vs self-contained documents
  versions/3.0.4.md
Labels: clarification

#4081 Minor param serialization and wording fixes
  versions/3.0.4.md
Labels: param serialization, editorial

#4088 Port of last-minute 3.0.4 changes to 3.1.1
  versions/3.1.1.md
Labels: links, clarification, param serialization, re-use: ref/id resolution, editorial

#4090 Move complex Sec Req example to appendix F
  versions/3.0.4.md
Labels: re-use: ref/id resolution

#4091 3.1.1 port of Move complex Sec Req example to appendix F
  versions/3.1.1.md
Labels: re-use: ref/id resolution

#4063 [PROPOSAL] Add summary, parent and kind as optional fields for tags
  proposals/2024-09-01-Tags-Improvement.md
Labels: draft:proposal, metadata

#4097 Update release process notes
  DEVELOPMENT.md
Labels: Process

#4109 3.0.4: use specific custom languages uri and uritemplate
  versions/3.0.4.md
Labels: editorial

#4113 Add in new full-TSC members
  MAINTAINERS.md
Labels: Housekeeping

#4110 3.1.1: use specific custom languages uri and uritemplate
  versions/3.1.1.md
Labels: editorial, approved pr port

#4107 ReSpec build script: no automatic syntax highlighting for unspecified or "unknown" languages
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-new.md
Labels: Housekeeping

#4111 Annotated enums and extended validation
  scripts/format-markdown.sh
  versions/3.1.1.md
Labels: schema-object, clarification
