Repository OAI/OpenAPI-Specification, pull requests merged in 2024-06, with the labels that each got.

#3846 Clarify discriminator + oneOf/anyOf/allOf usage (3.1.1 modified port of #3822)
  versions/3.1.1.md
Labels: discriminator, clarification

#3824 Clarify Link Obj parameters as best we can (3.0.4)
  versions/3.0.4.md
Labels: links, clarification

#3871 Add level2 headings to Security Considerations doc
  SECURITY_CONSIDERATIONS.md
Labels: security, security: meta

#3880 Backport (3.0.4) of merge resolution from #3846
  versions/3.0.4.md
Labels: discriminator, clarification, approved pr port

#3881 OpenID Connect Core URL fix (3.1.1 port of #3607)
  versions/3.1.1.md
Labels: security, approved pr port

#3882 OpenID Connect Discovery URL fix (3.0.4 port of #3718)
  versions/3.0.4.md
Labels: security, approved pr port

#3885 Clarify discriminator + oneOf/anyOf/allOf usage (3.2.0 port of #3846)
  versions/3.2.0.md
Labels: discriminator, clarification, approved pr port

#3883 Clarify Link Obj parameters as best we can (3.1.1 port of #3824)
  versions/3.1.1.md
Labels: links, clarification, approved pr port

#3838 Clarify "URI" and "URL" meaning and usage (3.1.1)
  versions/3.1.1.md
Labels: clarification, re-use: ref/id resolution

#3858 Resolution of relative URLs in CommonMark text (3.0.4)
  versions/3.0.4.md
Labels: clarification, metadata, re-use: ref/id resolution

#3860 Path Item $ref change warning (3.1.1)
  versions/3.1.1.md
Labels: bug, re-use: traits/merges, re-use: ref/id resolution

#3884 Clarify Link Obj parameters as best we can (3.2.0 port of #3824)
  versions/3.2.0.md
Labels: links, clarification, approved pr port

#3893 Consolidate guidance around examples (3.0.4)
  versions/3.0.4.md
Labels: bug, clarification, example obj/keywords

#3895 Consolidate guidance around examples (modified 3.1.1 port of #3893)
  versions/3.1.1.md
Labels: bug, clarification, example obj/keywords

#3892 Resolution of relative URLs in CommonMark text (3.1.1 port of #3858)
  versions/3.1.1.md
Labels: clarification, metadata, re-use: ref/id resolution, approved pr port

#3862 Minor webhooks/callbacks and schema `examples` improvements (3.1.1)
  versions/3.1.1.md
Labels: clarification, editorial

#3867 Verbose Header Object documentation (3.0.4)
  versions/3.0.4.md
Labels: clarification, headers

#3864 Improve media type serialization examples (3.0.4)
  versions/3.0.4.md
Labels: examples, clarification, media and encoding

#3840 Appendix on converting data types to strings (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization, media and encoding

#3841 Warnings for header and cookie serialization (3.0.4)
  versions/3.0.4.md
Labels: param serialization, headers

#3894 Add Security Considerations (3.0.4)
  versions/3.0.4.md
Labels: security, security: meta

#3900 Update ReSpec versions for Arazzo
  arazzo/latest.html
  arazzo/v1.0.0.html
Labels: Housekeeping

#3857 Encoding Object content and header clarifications (3.0.4)
  versions/3.0.4.md
Labels: clarification, media and encoding

#3856 Alternative: Clarify resolving implicit connections (3.1.1- alternative to #3823)
  versions/3.1.1.md
Labels: clarification, re-use: globals/defaults, re-use: ref/id resolution

#3859 Appendix for percent-encoding concerns (3.0.4)
  versions/3.0.4.md
Labels: clarification, param serialization, media and encoding

#3904 Fix heading levels
  versions/3.0.4.md
Labels: bug

#3917 Include Header Object in data serialization list
  versions/3.0.4.md
Labels: clarification, headers

#3905 Fix XML namespace syntax
  versions/3.0.4.md
Labels: bug, xml

#3906 Resolving implicit connections (3.0.4 port of #3856)
  versions/3.0.4.md
Labels: clarification, re-use: ref/id resolution, approved pr port

#3907 Clarify discriminator non-impact on validation
  versions/3.0.4.md
Labels: discriminator, clarification

#3911 Fix stray mentions of parameters in Encoding / Header Objects (3.0.4)
  versions/3.0.4.md
Labels: bug, param serialization, media and encoding, headers

#3919 Consisent x- Param/Encoding/Header wording (3.0.4)
  versions/3.0.4.md
Labels: bug, param serialization, headers, editorial

#3909 More guidance on schema dialects.
  versions/3.1.1.md
Labels: schema-object, clarification

#3891 OIDC fixes (3.2.0 port of #3607, #3718)
  versions/3.2.0.md
Labels: security, approved pr port

#3920 Minor editiorial and link target fixes (3.0.4)
  versions/3.0.4.md
Labels: bug, editorial

#3908 Use document/description/definition consistently (3.0.4)
  versions/3.0.4.md
Labels: editorial

#3924 3.0.4 dev: typo "paramter"
  versions/3.0.4.md
Labels: bug

#3921 Port remaining 3.0.4 fixes with adjustments for 3.1.1
  versions/3.1.1.md
Labels: bug, links, discriminator, clarification, param serialization, media and encoding, metadata, headers, editorial, registries

#3923 Reorganize and streamline form media type guidance (3.0.4)
  versions/3.0.4.md
Labels: clarification, media and encoding

#3927 Authoritative rendering; "schema" usage (3.0.4)
  versions/3.0.4.md
Labels: clarification, editorial

#3922 format: byte also defaults to octet-stream (3.0.4)
  versions/3.0.4.md
Labels: bug, media and encoding

#3926 Port a few more fixes to 3.1.1
  versions/3.1.1.md
Labels: bug, editorial

#3933 3.0.4 formatting: don't monospace "Xxx Object"
  versions/3.0.4.md
Labels: editorial

#3929 Clarify interaction of format: byte and Content-Transfer-Encoding header definition
  versions/3.0.4.md
Labels: clarification, media and encoding
