Repository OAI/OpenAPI-Specification, pull requests merged in 2025-07, with the labels that each got.

#4760 feat: add date-time-local and time-local.
  registries/_format/date-time-local.md
  registries/_format/time-local.md
Labels: format-registry, registries

#4740 v3.2: Add support for application/linkset[+json]
  src/oas.md
Labels: media and encoding, headers

#4790 v3.2: Move URI/URL resolution sections, *UNCHANGED*, under OAD Structure
  src/oas.md
Labels: editorial

#4797 v3.2: Editorial improvements to Appendix E (Percent-Encoding)
  src/oas.md
Labels: editorial

#4728 v3.2: Allow Media Type Object re-use
  src/oas.md
  src/schemas/validation/schema.yaml
  tests/schema/pass/media-type-examples.yaml
Labels: media and encoding

#4747 v3.2: Support nested multipart with nested Encoding Objects
  src/oas.md
  src/schemas/validation/schema.yaml
  tests/schema/fail/encoding-enc-item-exclusion.yaml
  tests/schema/fail/encoding-enc-prefix-exclusion.yaml
  tests/schema/pass/media-type-examples.yaml
Labels: media and encoding

#4812 v3.2: Move a paragraph, unchanged, to make more sense in multipart encoding
  src/oas.md
Labels: media and encoding, editorial

#4799 v3.2 Add data vs serialized example fields (3rd try)
  src/oas.md
  src/schemas/validation/schema.yaml
  tests/schema/fail/example-object-old-exclusions.yaml
  tests/schema/fail/example-object-old-vs-data.yaml
  tests/schema/fail/example-object-old-vs-ser.yaml
  tests/schema/fail/example-object-ser-exclusions.yaml
  tests/schema/pass/example-object-examples.yaml
Labels: media and encoding, example obj/keywords

#4800 v3.2: Explain Param and Header example serialization
  src/oas.md
Labels: param serialization, media and encoding

#4745 v3.2: (Split and smaller!) Support ordered multipart including streaming
  src/oas.md
  src/schemas/validation/schema.yaml
  tests/schema/fail/media-type-enc-item-exclusion.yaml
  tests/schema/fail/media-type-enc-prefix-exclusion.yaml
  tests/schema/pass/media-type-examples.yaml
Labels: media and encoding

#4711 v3.2: XML Object example updates
  src/oas.md
Labels: xml, example obj/keywords
