Repository OAI/OpenAPI-Specification, pull requests merged in 2025-09, with the labels that each got.

#4913 v3.2-dev Small post-section-reorg fixes
  src/oas.md
Labels: editorial

#4952 3.2 Server-Sent Event Streams: use current section heading as link text
  src/oas.md
Labels: editorial

#4948 3.2 Style Examples: consistent formatting
  src/oas.md
Labels: editorial

#4947 3.2 Serialization and Examples: remove unnecessary sentence
  src/oas.md
Labels: editorial

#4941 3.2 broken link for "implicit connections"
  src/oas.md
Labels: bug, editorial

#4957 v3.2 schema edits
  src/schemas/validation/schema.yaml
  tests/schema/fail/example-examples.yaml
  tests/schema/fail/invalid_schema_types.yaml
  tests/schema/fail/operation-object-query-with-querystring.yaml
  tests/schema/fail/operation-object-two-querystrings.yaml
  tests/schema/fail/path-item-object-query-with-querystring.yaml
  tests/schema/fail/path-item-object-two-querystrings.yaml
  tests/schema/pass/example-object-examples.yaml
  tests/schema/pass/parameter-object-examples.yaml
  tests/schema/pass/schema-object-deprecated-example-keyword.yaml
Labels: Schema

#4808 Media Types Registry
  _config.yml
  _includes/media-type-entry.md
  registries/_media-type/binary.md
  registries/_media-type/forms.md
  registries/_media-type/linksets.md
  registries/_media-type/sequential_json.md
  registries/_media-type/sequential_multipart.md
  registries/_media-type/sse.md
  registries/_media-type/text.md
  registries/_media-type/xml.md
  registry/media-type.md
Labels: registries

#4987 3.2.1: Fix dead anchor links to appendix
  src/oas.md
Labels: editorial
