Repository OAI/OpenAPI-Specification, pull requests merged in 2025-08, with the labels that each got.

#4820 v3.1.2: Fix guidance for RFC6570 and multipart/form-data
  src/oas.md
Labels: clarification, media and encoding

#4829 dev: update from main
  .github/workflows/sync-dev-to-vX.Y-dev.yaml
  package-lock.json
  package.json
  scripts/adjust-release-branch.sh
  tests/schema/oas-schema.mjs
  vitest.config.mjs
Labels: Housekeeping

#4826 v3.1.2: Explain Param and Header example serialization (backports PR 4800)
  src/oas.md
Labels: clarification, param serialization, media and encoding, approved pr port

#4856 3.2 schema tests: keyword coverage
  tests/schema/pass/link-object-examples.yaml
  tests/schema/pass/schema-object-deprecated-example-keyword.yaml
  tests/schema/pass/specification-extensions.yaml
  tests/schema/schema.test.mjs
Labels: Schema, approved pr port

#4864 v3.2 [TRIVIAL] Remove duplicate field in YAML example
  src/oas.md
Labels: bug, examples

#4877 3.1 Runtime Expression ABNF: use exact same name as in RFC7159
  src/oas.md
Labels: editorial

#4868 v3.1.2: Fix Link Object subsections, improve examples
  src/oas.md
Labels: links, examples, clarification, editorial

#4887 gh-pages: fix uplinks from registry entry to registry page
  _includes/alternative-schema-entry.md
  _includes/extension-entry.md
  _includes/format-entry.md
  _includes/namespace-entry.md
  _includes/tag-kind-entry.md
  registries/_draft-feature/alternativeSchema.md
Labels: Housekeeping

#4881 main CONTRIBUTING.md: update Publishing section
  CONTRIBUTING.md
Labels: Housekeeping, editorial

#4876 3.2 typos and minor editorial changes
  src/oas.md
Labels: editorial

#4899 v3.2: Enc style defaults
  src/oas.md
Labels: media and encoding

#4905 v3.2: Update RFC1866 to WHATWG-URL for application/x-www-form-urlencoded
  src/oas.md
Labels: clarification, param serialization, media and encoding
