Repository OAI/OpenAPI-Specification, pull requests merged in 2025-05, with the labels that each got.

#4552 v3.2: format-markdown on src/oas.md
  src/oas.md
Labels: editorial

#4559 v3.2 Respect `encoding` in all Media Type Objects
  src/oas.md
Labels: media and encoding

#4562 v3.2 Arrange encoding information more clearly
  src/oas.md
Labels: media and encoding

#4553 highlight.js: support for JSONL, JSON-Seq, basic multipart, improve text/event-stream
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-new.md
Labels: script

#4554 v3.2: Sequential/streaming media types (take 2)
  src/oas.md
  src/schemas/validation/schema.yaml
  tests/schema/pass/media-type-examples.yaml
Labels: media and encoding

#4579 Allow IRIs for XML namespaces
  src/oas.md
  src/schemas/validation/meta.yaml
Labels: enhancement, xml, media and encoding

#4573 v3.2: Port of 3.1.2 changes to 3.2
  src/oas.md
  src/schemas/validation/schema.yaml
Labels: media and encoding, editorial, approved pr port

#4577 v3.2: Only use YAML for examples
  src/oas.md
Labels: editorial

#4591 v3.2: Define a policy for deprecation markings.
  src/oas.md
Labels: clarification, editorial

#4614 v3.1.2: Clarify that Request Body Objects need a body
  src/oas.md
Labels: clarification, media and encoding

#4576 v3.1.2: Root XML element name comes from component name
  src/oas.md
Labels: xml, clarification, media and encoding

#4612 v3.1.2: Provide guidance on null in XML.
  src/oas.md
Labels: xml, clarification, media and encoding

#4630 v3.2: Add "summary" field to Response Object
  src/oas.md
  src/schemas/validation/schema.yaml
Labels: enhancement, metadata

#4638 main: avoid unconventional use of yargs
  scripts/md2html/md2html.js
  vitest.config.mjs
Labels: Housekeeping, javascript
