Repository OAI/OpenAPI-Specification, pull requests merged in 2025-02, with the labels that each got.

#4268 Add dark mode support to the HTML versions of the OpenAPI specs
  scripts/md2html/main.css
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-old.html
Labels: Housekeeping

#4328 Adjust uri to uri-reference for security schema fixed fields
  schemas/v3.1/schema.yaml
Labels: Schema

#4331 3.1: consistent style for field names and values in YAML comments
  CONTRIBUTING.md
  src/oas.md
Labels: editorial

#4336 dev: format src/oas.md
  package.json
Labels: Housekeeping

#4358 Run respec without sandbox
  scripts/md2html/build.sh
Labels: script

#4360 3.1: adjust uri to uri-reference for security schema fixed fields (now in src)
  src/schemas/validation/schema.yaml
Labels: Schema, Housekeeping

#4369 dev: use common spec build script for building from src/oas.md
  package.json
  scripts/md2html/build-src.sh
Labels: Housekeeping, script

#4363 Describe spec and schema publishing process
  CONTRIBUTING.md
Labels: Housekeeping, Process

#4377 main: update style-guide.md - consistent style for field names and values in YAML comments
  style-guide.md
Labels: Housekeeping

#4365 gh-pages: show OAS 2.0 spec
  .gitignore
  _includes/specification-version-list.md
  index.md
Labels: Housekeeping
