Repository OAI/OpenAPI-Specification, pull requests merged in 2025-04, with the labels that each got.

#4503 3.2 Use human-friendly rendering of JSON Schema I-D
  src/oas.md
Labels: editorial

#4480 Proposal for referencing Tag Objects with URIs.
  proposals/2025-03-20-URIs-for-Tags.md
Labels: metadata

#4505 3.2: Remove promise of URIs for tags, note alternatives
  src/oas.md
Labels: clarification, metadata

#4468 3.1: schema test coverage 100%
  tests/schema/fail/link-object-no-body.yaml
  tests/schema/pass/callback-object-examples.yaml
  tests/schema/pass/components-object-example.yaml
  tests/schema/pass/example-object-examples.yaml
  tests/schema/pass/header-object-examples.yaml
  tests/schema/pass/info-object-example.yaml
  tests/schema/pass/link-object-examples.yaml
  tests/schema/pass/media-type-examples.yaml
  tests/schema/pass/operation-object-example.yaml
  tests/schema/pass/parameter-object-examples.yaml
  tests/schema/pass/path-item-object-example.yaml
  tests/schema/pass/paths-object-example.yaml
  tests/schema/pass/request-body-examples.yaml
  tests/schema/pass/response-object-examples.yaml
  tests/schema/pass/security-scheme-object-examples.yaml
  tests/schema/pass/servers.yaml
  tests/schema/pass/tag-object-example.yaml
Labels: Schema, approved pr port
