Repository OAI/OpenAPI-Specification, pull requests merged in 2025-01, with the labels that each got.

#4294 Fix copy-paste "format: binary" error
  src/oas.md
Labels: bug, examples

#4254 dev: build HTML from src/oas.md
  .gitignore
  CONTRIBUTING.md
  package.json
  scripts/md2html/build-src.sh
Labels: Housekeeping, script

#4301 More contentEncoding example improvements (from feedback)
  src/oas.md
Labels: examples, clarification

#4311 dev: validate markdown in build-src
  CONTRIBUTING.md
  package.json
Labels: Housekeeping

#4304 docs: adds ms extensions repo link
  registries/_namespace/ms.md
Labels: registries

#4318 Use branch-local package-lock.json
  .github/workflows/schema-tests.yaml
  .github/workflows/validate-markdown.yaml
Labels: Housekeeping

#4322 Update schema-tests.yaml: correct step description
  .github/workflows/schema-tests.yaml
Labels: Housekeeping
