Repository OAI/OpenAPI-Specification, pull requests merged in 2025-06, with the labels that each got.

#4689 3.2: bring schema test coverage back to 100%
  tests/schema/pass/info-object-example.yaml
  tests/schema/pass/parameter-object-examples.yaml
  tests/schema/pass/response-object-examples.yaml
Labels: Schema

#4688 Fail if schema test coverage is below 100%, except on dev
  scripts/schema-test-coverage.mjs
  scripts/schema-test-coverage.sh
Labels: Housekeeping, script

#4667 Typo in section „Sequential Media Types“
  src/oas.md
Labels: editorial

#4703 Test Schema Object extension fields on v3.1-dev
  tests/schema/pass/json_schema_dialect.yaml
  tests/schema/pass/media-type-examples.yaml
  tests/schema/pass/mega.yaml
Labels: script

#4701 Use full schema (schema-base.yaml) for coverage
  scripts/schema-test-coverage.mjs
  scripts/schema-test-coverage.sh
Labels: script

#4592 v3.2: Support all common XML node types (element, attribute, text, cdata)
  src/oas.md
  src/schemas/validation/meta.yaml
  tests/schema/fail/xml-attr-exclusion.yaml
  tests/schema/fail/xml-wrapped-exclusion.yaml
  tests/schema/pass/media-type-examples.yaml
Labels: enhancement, xml, media and encoding

#4657 v3.2: Strengthen generic data types to a SHOULD
  src/oas.md
Labels: schema-object

#4726 v3.2: (port of #4614) Clarify that Request Body Objects need a body
  src/oas.md
Labels: approved pr port

#4730 sync workflows: use app token to trigger PR event
  .github/workflows/sync-dev-to-vX.Y-dev.yaml
  .github/workflows/sync-main-to-dev.yaml
Labels: Housekeeping, script
