Repository OAI/OpenAPI-Specification, pull requests merged in 2025-03, with the labels that each got.

#4382 style guide: no requirements in "Examples" sections
  style-guide.md
Labels: editorial

#4401 main: add "Other versions" links to frontmatter of HTML-rendered specs
  scripts/md2html/build.sh
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-old.html
  tests/md2html/md2html.test.mjs
Labels: Housekeeping, script

#4393 main: new workflow that syncs main to dev
  .github/workflows/sync-main-to-dev.yaml
  CONTRIBUTING.md
Labels: Housekeeping

#4394 3.2 schema: new fixed fields in Security Scheme Object
  src/schemas/validation/schema.yaml
Labels: Schema

#4436 main: sync CONTRIBUTING.md from dev
  CONTRIBUTING.md
Labels: Housekeeping, approved pr port

#4403 Repair Google Tag Manager
  scripts/md2html/build.sh
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-old.html
Labels: Housekeeping

#4434 gh-pages: Delete Dockerfile
  Dockerfile
Labels: Housekeeping

#4366 gh-pages: show OAS 2.0 schema
  _includes/schema-iteration-list.md
  oas/2.0/schema/2017-08-27
  oas/2.0/schema/2017-08-27.md
Labels: Schema, Housekeeping

#4339 Allow discriminator to be optional
  src/oas.md
Labels: discriminator

#4435 main: move old schemas to _archive_
  .gitignore
  README.md
  _archive_/README.md
  _archive_/schemas/README.md
  _archive_/schemas/v1.2/README.md
  _archive_/schemas/v1.2/apiDeclaration.json
  _archive_/schemas/v1.2/authorizationObject.json
  _archive_/schemas/v1.2/dataType.json
  _archive_/schemas/v1.2/dataTypeBase.json
  _archive_/schemas/v1.2/infoObject.json
  _archive_/schemas/v1.2/modelsObject.json
  _archive_/schemas/v1.2/oauth2GrantType.json
  _archive_/schemas/v1.2/operationObject.json
  _archive_/schemas/v1.2/parameterObject.json
  _archive_/schemas/v1.2/resourceListing.json
  _archive_/schemas/v1.2/resourceObject.json
  _archive_/schemas/v2.0/README.md
  _archive_/schemas/v2.0/schema.json
  _archive_/schemas/v3.0/README.md
  _archive_/schemas/v3.0/pass/api-with-examples.yaml
  _archive_/schemas/v3.0/pass/callback-example.yaml
  _archive_/schemas/v3.0/pass/link-example.yaml
  _archive_/schemas/v3.0/pass/petstore-expanded.yaml
  _archive_/schemas/v3.0/pass/petstore.yaml
  _archive_/schemas/v3.0/pass/uspto.yaml
  _archive_/schemas/v3.0/schema.test.mjs
  _archive_/schemas/v3.0/schema.yaml
  schemas/v3.1/README.md
  schemas/v3.1/dialect.yaml
  schemas/v3.1/meta.yaml
  schemas/v3.1/schema-base.yaml
  schemas/v3.1/schema.yaml
  scripts/schema-test-coverage.sh
  tests/v3.1/fail/invalid_schema_types.yaml
  tests/v3.1/fail/no_containers.yaml
  tests/v3.1/fail/server_enum_empty.yaml
  tests/v3.1/fail/servers.yaml
  tests/v3.1/fail/unknown_container.yaml
  tests/v3.1/pass/comp_pathitems.yaml
  tests/v3.1/pass/info_summary.yaml
  tests/v3.1/pass/license_identifier.yaml
  tests/v3.1/pass/mega.yaml
  tests/v3.1/pass/minimal_comp.yaml
  tests/v3.1/pass/minimal_hooks.yaml
  tests/v3.1/pass/minimal_paths.yaml
  tests/v3.1/pass/non-oauth-scopes.yaml
  tests/v3.1/pass/path_no_response.yaml
  tests/v3.1/pass/path_var_empty_pathitem.yaml
  tests/v3.1/pass/schema.yaml
  tests/v3.1/pass/servers.yaml
  tests/v3.1/pass/valid_schema_types.yaml
  tests/v3.1/pass/webhook-example.yaml
  tests/v3.1/schema.test.mjs
Labels: Schema, Housekeeping

#4367 3.2: bump spec version in schema files
  src/schemas/validation/dialect.yaml
  src/schemas/validation/meta.yaml
  src/schemas/validation/schema-base.yaml
  src/schemas/validation/schema.yaml
  tests/schema/fail/invalid_schema_types.yaml
  tests/schema/fail/no_containers.yaml
  tests/schema/fail/server_enum_empty.yaml
  tests/schema/fail/servers.yaml
  tests/schema/fail/unknown_container.yaml
  tests/schema/pass/comp_pathitems.yaml
  tests/schema/pass/info_summary.yaml
  tests/schema/pass/license_identifier.yaml
  tests/schema/pass/mega.yaml
  tests/schema/pass/minimal_comp.yaml
  tests/schema/pass/minimal_hooks.yaml
  tests/schema/pass/minimal_paths.yaml
  tests/schema/pass/non-oauth-scopes.yaml
  tests/schema/pass/path_no_response.yaml
  tests/schema/pass/path_var_empty_pathitem.yaml
  tests/schema/pass/schema.yaml
  tests/schema/pass/servers.yaml
  tests/schema/pass/valid_schema_types.yaml
  tests/schema/pass/webhook-example.yaml
Labels: Schema, editorial

#4380 3.2: reference RFC 9110 instead of RFCs 7230, 7231, and 7235
  src/oas.md
Labels: editorial

#4456 3.2: schema test coverage
  src/schemas/validation/schema.yaml
  tests/schema/pass/callback-object-examples.yaml
  tests/schema/pass/components-object-example.yaml
  tests/schema/pass/example-object-examples.yaml
  tests/schema/pass/header-object-examples.yaml
  tests/schema/pass/info-object-example.yaml
  tests/schema/pass/link-object-examples.yaml
  tests/schema/pass/media-type-examples.yaml
  tests/schema/pass/operation-object-example.yaml
  tests/schema/pass/parameter-object-examples.yaml
  tests/schema/pass/path-item-object-example.yaml
  tests/schema/pass/path_item_servers_parameters.yaml
  tests/schema/pass/paths-object-example.yaml
  tests/schema/pass/request-body-examples.yaml
  tests/schema/pass/response-object-examples.yaml
  tests/schema/pass/security-scheme-object-examples.yaml
  tests/schema/pass/servers.yaml
  tests/schema/pass/tag-object-example.yaml
Labels: Schema

#4465 3.1: fix Link Object schema
  src/schemas/validation/schema.yaml
  tests/schema/pass/path_item_servers_parameters.yaml
Labels: Schema

#4462 main: hint for using npm scripts on Windows
  CONTRIBUTING.md
Labels: Housekeeping, editorial

#4486 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, Housekeeping

#4452 main: package.json is only for infrastructure
  package.json
Labels: Housekeeping, editorial

#4467 3.2: reference latest JSON Schema 2020-12 drafts
  src/oas.md
Labels: editorial

#4388 Allow URIs for Security Schemes
  src/oas.md
Labels: enhancement, re-use: ref/id resolution

#4454 main: helper script for preparing a release branch
  CONTRIBUTING.md
  scripts/adjust-release-branch.sh
Labels: Housekeeping

#4494 main: CONTRIBUTING note on `buid-src` for Windows users
  CONTRIBUTING.md
Labels: Housekeeping, editorial

#4492 main: add and update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/registry_feature_request.md
  .github/ISSUE_TEMPLATE/spec_bug_report.md
Labels: Housekeeping

#4499 3.2: update normative reference for JSON to RFC8259
  src/oas.md
Labels: editorial

#4501 3.2: schema test case and schema bug fix for device authorization
  src/schemas/validation/schema.yaml
  tests/schema/pass/security-scheme-object-examples.yaml
Labels: Schema

#4507 Discrimator -> Discriminator
  src/oas.md
Labels: bug, editorial

#4516 Add highlight.js support for text/event-stream
  scripts/md2html/md2html.js
  tests/md2html/fixtures/basic-new.html
  tests/md2html/fixtures/basic-new.md
Labels: script
